---
- name: Converge
  hosts: all
  tasks:
    - name: Include collect_logs
      include_role:
        name: collect_logs
        tasks_from: sova.yml
      tags:
        - molecule-idempotence-notest
