---
- name: Prepare
  hosts: all
  tasks:

    - name: Prepare the console file directory
      file:
        path: '{{ ansible_user_dir }}/workspace/logs/'
        state: directory
        mode: 0755

    - name: Create a sample console file
      copy:
        content: |
          No valid host was found. There are not enough hosts
        dest: '{{ ansible_user_dir }}/workspace/logs/quickstart_install.log'
        mode: 0644

    - name: Create a sample sova config file
      copy:
        content: |
          {
            "patterns": {
               "bmc": [
                  {
                    "id": "Introspection_failed_cannot_get_IP_address",
                     "logstash": "",
                      "msg": "Introspection failed, cannot get IP address",
                      "pattern": "Introspection_failed_cannot_get_IP_address",
                      "tag": "infra"
                  }
                ],
                "console": [
                  {
                      "id": "Not_enough_hosts",
                      "logstash": "",
                      "msg": "No valid host was found.",
                      "pattern": "Not_enough_hosts",
                      "tag": "info"
                  }
                ],
                "errors": [
                  {
                      "id": "Buildah_pull_image_failed",
                      "logstash": "",
                      "msg": "Buildah pull image failed",
                      "pattern": "Buildah_pull_image_failed",
                      "tag": "info"
                  }
                ],
                "ironic-conductor": [
                  {
                      "id": "Ironic_deployment_timeout",
                      "logstash": "",
                      "msg": "Ironic deployment timeout.",
                      "pattern": "Ironic_deployment_timeout",
                      "tag": "info"
                  }
                ],
                "logstash": [
                  {
                    "id": "Ping_timeout_when_deploying_OC",
                    "logstash": "",
                    "msg": "Ping timeout when deploying OC.",
                    "pattern": "Ping_timeout_when_deploying_OC",
                    "tag": "infra"
                  }
                ],
                "registry_log": [
                  {
                    "id": "Invalid_checksum_format",
                    "logstash": "",
                    "msg": "Invalid checksum format.",
                    "pattern": "Invalid_checksum_format",
                    "tag": "infra"
                  }
                ],
                "selinux": [
                  {
                    "id": "selinux_denials_found",
                    "logstash": "",
                    "msg": "selinux denials found",
                    "pattern": "selinux_denials_found",
                    "tag": "code"
                  }
                ],
                "syslog": [
                  {
                    "id": "service_FAIL",
                    "logstash": "",
                    "msg": "service FAIL",
                    "pattern": "service_FAIL",
                    "tag": "command_exe"
                  }
                ]
              },
            "regexes": [
              {
                "name": "Not_enough_hosts",
                "regex": "No\\ valid\\ host\\ was\\ found\\.\\ There\\ are\\ not\\ enough\\ hosts"
              }
            ]
          }
        dest: '{{ ansible_user_dir }}/workspace/logs/sova_config.json'
        mode: 0644
