---
name: collect_logs
namespace: tripleo
version: 0.0.1
authors:
  - tripleo
readme: README.rst

build_ignore:
  - .ansible
  - .cache
  - .github
  - .gitignore
  - .pytest_cache
  - .vscode
  - .tox
  - dist
  - tox.ini
  - .eggs
  - .mypy_cache
  - "*.egg-info"
  - modules
  - module_utils
  - infrared_plugin
  - scripts
