---
- hosts: all
  tasks:

    - name: Remove docker from molecule
      become: true
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: absent

    - name: Set containers module to 3.0
      become: true
      shell: |
        dnf module disable container-tools:rhel8 -y
        dnf module enable container-tools:3.0 -y
        dnf clean metadata
      tags:
        - skip_ansible_lint

    - name: Install podman
      include_role:
        name: ensure-podman
