---
driver:
  name: podman
log: true
platforms:
  # - name: centos7
  #   image: quay.io/pycontribs/centos7
  #   pre_build_image: true
  - name: centos8
    # image below is based on official quay.io/centos/centos:stream8 but
    # it has python preinstalled on it.
    image: quay.io/pycontribs/centos:stream8
    pre_build_image: true
  # - name: debian
  #   image: quay.io/pycontribs/3.8-slim-buster
  #   pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto
      forks: 50
      stdout_callback: yaml
      timeout: 30
  inventory:
    group_vars:
      all:
        local_working_dir: "{{ lookup('env', 'TOX_ENV_DIR') or '~/.cache' }}/log"
        artcl_gzip: true
        artcl_min_size: 500000  # ~0.5mb
        infrared_location: "~/ir"
        infrared_venv: "{{ infrared_location }}/.infrared"
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - verify
    - cleanup
    - destroy
markers:
  - xfail  # https://projects.engineering.redhat.com/browse/RHOSINFRA-4174
