---
- name: gather facts used by role
  setup:
    gather_subset: "!min,pkg_mgr,python"
  when: "['pkg_mgr', 'python'] | difference(ansible_facts.keys()|list)"

- name: Load unsecure.yml defaults when outside zuul
  when: zuul is not defined
  include_vars: unsecure.yml

- name: Load operating system specific variables
  include_vars: "{{ item }}"
  failed_when: false
  # pattern: v3
  loop:
    - "family-{{ ansible_os_family | lower }}.yml"
    - "family-{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower | replace(' ', '-') }}.yml"
    - "{{ ansible_distribution | lower | replace(' ', '-') }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower | replace(' ', '-') }}-{{ ansible_distribution_version.split('.')[0:2] | join('-') | lower }}.yml"
  tags:
    - always

- name: Collect logs
  include: collect.yml
  when: artcl_collect|bool

- name: Generate docs
  include: create-docs.yml
  when:
    - artcl_gen_docs|bool
    - not artcl_collect|bool

- name: Publish logs
  include: publish.yml
  when:
    - artcl_publish|bool
    - not artcl_collect|bool

- name: Verify Sphinx build
  shell: |  # noqa 305
    grep -q "{{ item }}" "{{ artcl_collect_dir }}/docs/build/index.html"
  with_items: "{{ artcl_create_docs_payload.table_of_contents }}"
  changed_when: false
  when:
    - artcl_gen_docs|bool
    - artcl_verify_sphinx_build|bool
    - not artcl_collect|bool
