---
driver:
  name: docker
log: true
platforms:
  # - name: centos7
  #   image: quay.io/pycontribs/centos:centos7
  #   pre_build_image: true
  - name: centos8
    # image below is based on official quay.io/centos/centos:stream8 but
    # it has python preinstalled on it.
    image: quay.io/pycontribs/centos:stream8
    pre_build_image: true
  # - name: debian
  #   image: quay.io/pycontribs/python:3.8-slim-buster
  #   pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto
      forks: 50
      stdout_callback: yaml
      timeout: 30
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        local_working_dir: "{{ lookup('env', 'TOX_ENV_DIR') or '~/.cache' }}/log"
        artcl_ignore_errors: false
verifier:
  name: ansible
scenario:
  # custom because "idempotence" is not yet supported by the role
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
