---
driver:
  name: docker
log: true
platforms:
  - name: centos7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    # - name: centos8
    #   image: docker.io/pycontribs/centos:8
    #   pre_build_image: true
    # - name: ubuntu
    #   image: docker.io/pycontribs/ubuntu:latest
    #   pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto
      forks: 50
      stdout_callback: yaml
      timeout: 30
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        local_working_dir: "{{ lookup('env', 'TOX_ENV_DIR') or '~/.cache' }}/log"
        artcl_ignore_errors: false
verifier:
  name: ansible
scenario:
  # custom because "idempotence" is not yet supported by the role
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
