---
- name: Mock some logs
  hosts: all
  become: true
  tasks:

    - name: Generate bootstrap-subnodes.log
      copy:
        content: |
          2000-00-00T00:00:00.000Z | this is sparta
        dest: /var/log/bootstrap-subnodes.log
        mode: 0644

    - name: Remove /var/log/extra/logstash.txt
      file:
        path: /var/log/extra/logstash.txt
        state: absent
