---
- name: Validate "/var/log/extra/logstash.txt
  hosts: all
  tasks:

    - name: Check logstash.txt contains expected data
      shell: grep -q "this is sparta" /var/log/extra/logstash.txt
      changed_when: false
